# Generated by Django 3.1.2 on 2020-10-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentID', models.CharField(max_length=25)),
                ('agentName', models.CharField(max_length=50)),
                ('agentOccupation', models.CharField(max_length=50)),
                ('agency', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField(max_length=12)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
