# Generated by Django 3.1.2 on 2020-10-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
